/* =================================================================================
   Vault UI E2E — Static File Server
   Serves the vault UI at v0.2.4 from a single Node.js http server.

   Path mapping:
     /                     → index.html (root — hash inbox)
     /_common/**           → _common/** (shared assets)
     /en-gb/               → en-gb/index.html (landing page)
     /en-gb/vault/         → root index.html with _common/ rewritten to /_common/
                             (en-gb/vault/index.html is generated by run-locally.sh;
                             the server generates the equivalent on-the-fly)
     /en-gb/vault/peek/    → en-gb/vault/peek/index.html (standalone, no transforms)
     anything else         → 404

   Start: node tests/e2e/vault_ui/fixtures/vault-server.js <port>
   ================================================================================= */

import http   from 'node:http';
import fs     from 'node:fs';
import path   from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const VAULT_ROOT = path.resolve(__dirname, '../../../../sgraph_ai_app_send__ui__vault/v0/v0.2/v0.2.4');

const MIME = {
    '.html':  'text/html; charset=utf-8',
    '.css':   'text/css',
    '.js':    'application/javascript',
    '.json':  'application/json',
    '.woff2': 'font/woff2',
    '.woff':  'font/woff',
    '.png':   'image/png',
    '.svg':   'image/svg+xml',
    '.ico':   'image/x-icon',
};

function mime(filePath) {
    return MIME[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
}

function send(res, status, type, body) {
    res.writeHead(status, { 'Content-Type': type });
    res.end(body);
}

// Rewrite relative _common/ refs so they work when served from /en-gb/vault/.
function vaultShellify(html) {
    return html.replace(/(['"`])_common\//g, '$1/_common/');
}

export function createServer() {
    return http.createServer(function handler(req, res) {
        // Strip query string and hash; normalise trailing slash.
        let url = (req.url || '/').split('?')[0].split('#')[0];
        if (url !== '/' && url.endsWith('/')) url = url.slice(0, -1);

        // Root
        if (url === '/' || url === '/index.html') {
            const content = fs.readFileSync(path.join(VAULT_ROOT, 'index.html'), 'utf8');
            return send(res, 200, 'text/html; charset=utf-8', content);
        }

        // Vault shell — en-gb/vault/index.html doesn't exist (generated at runtime);
        // serve root index.html with _common/ refs rewritten to absolute paths.
        if (url === '/en-gb/vault') {
            const content = fs.readFileSync(path.join(VAULT_ROOT, 'index.html'), 'utf8');
            return send(res, 200, 'text/html; charset=utf-8', vaultShellify(content));
        }

        // Attempt to serve the file directly.
        const fsPath = path.join(VAULT_ROOT, url);
        if (fs.existsSync(fsPath)) {
            const stat = fs.statSync(fsPath);
            if (stat.isDirectory()) {
                const indexPath = path.join(fsPath, 'index.html');
                if (fs.existsSync(indexPath)) {
                    return send(res, 200, 'text/html; charset=utf-8',
                        fs.readFileSync(indexPath, 'utf8'));
                }
            } else {
                return send(res, 200, mime(fsPath), fs.readFileSync(fsPath));
            }
        }

        send(res, 404, 'text/plain', 'Not found: ' + url);
    });
}

// ── CLI entry-point (called by Playwright webServer config) ──────────────────

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const port = parseInt(process.argv[2] || '3999', 10);
    createServer().listen(port, () => {
        console.log(`Vault UI test server: http://localhost:${port}`);
    });
}
