#!/usr/bin/env bash
# Vault loader unit test runner.
# Run from repo root: npm run test:vault-unit
# Or directly: bash tests/unit/vault_ui/loader/run-all.sh
set -e

echo "=== Vault UI unit tests ==="
node tests/unit/vault_ui/loader/test__format_detection.js
node tests/unit/vault_ui/loader/test__storage.js
node tests/unit/vault_ui/loader/test__recent_list.js
node tests/unit/vault_ui/loader/test__routing_decisions.js
node tests/unit/vault_ui/loader/test__public_preview_crypto.js
node tests/unit/vault_ui/loader/test__vault_links.js
node tests/unit/vault_ui/loader/test__composite_data_source.js
node tests/unit/vault_ui/loader/test__storage_pertab.js
node tests/unit/vault_ui/loader/test__vault_history.js
node tests/unit/vault_ui/loader/test__ro_record_derivation.js
node tests/unit/vault_ui/loader/test__read_key_creds.js
node tests/unit/vault_ui/loader/test__sgit_key_prefixes.js
node tests/unit/vault_ui/loader/test__vault_loader_open_readonly.js
node tests/unit/vault_ui/loader/test__vault_settings_readonly.js
node tests/unit/vault_ui/loader/test__vault_settings_file_listing.js
node tests/unit/vault_ui/loader/test__sgsend_access_token.js
node tests/unit/vault_ui/loader/test__sgsend_static_mode.js
node tests/unit/vault_ui/loader/test__sg_releases.js
node tests/unit/vault_ui/loader/test__pinned_data_source.js
node tests/unit/vault_ui/loader/test__vault_releases_editor.js
node tests/unit/vault_ui/loader/test__sg_llm_config.js
node tests/unit/vault_ui/loader/test__sg_llm.js
node tests/unit/vault_ui/loader/test__sg_llm_vault.js
node tests/unit/vault_ui/loader/test__sg_llm_tools.js
node tests/unit/vault_ui/loader/test__llm_hardening.js
node tests/unit/vault_ui/loader/test__llm_p4.js
node tests/unit/vault_ui/loader/test__sg_voice.js
node tests/unit/vault_ui/loader/test__sg_vision.js
node tests/unit/vault_ui/loader/test__no_auto_reload.js
node tests/unit/vault_ui/loader/test__base64_chunk_guard.js
node tests/unit/vault_ui/loader/test__send_browse_split.js
node tests/unit/vault_ui/loader/test__vault_llm_log.js
node tests/unit/vault_ui/loader/test__vault_llm_chat.js
node tests/unit/vault_ui/loader/test__vault_shell_llm_panels.js
node tests/unit/vault_ui/loader/test__app_page_llm_panels.js
node tests/unit/vault_ui/loader/test__vault_llm_requests.js
node tests/unit/vault_ui/loader/test__vault_browse_edit__add_to_chat.js
node tests/unit/vault_ui/loader/test__app_permissions.js
node tests/unit/vault_ui/loader/test__app_permissions__append.js
node tests/unit/vault_ui/loader/test__app_host_events.js
node tests/unit/vault_ui/loader/test__secure_channel_envelope.js
node tests/unit/vault_ui/loader/test__secure_channel.js
node tests/unit/vault_ui/loader/test__kernel_mounts.js
node tests/unit/vault_ui/loader/test__kernel_broker.js
node tests/unit/vault_ui/loader/test__kernel_relay.js
node tests/unit/vault_ui/loader/test__kernel_app_handlers.js
node tests/unit/vault_ui/loader/test__kernel_bootstrap.js
node tests/unit/vault_ui/loader/test__kernel_parent.js
node tests/unit/vault_ui/loader/test__viv_mounts_view.js
node tests/unit/vault_ui/loader/test__viv_audit_view.js
node tests/unit/vault_ui/loader/test__vault_subvaults_view.js
node tests/unit/vault_ui/loader/test__sg_repl_core.js
node tests/unit/vault_ui/loader/test__viv_custody.js
node tests/unit/vault_ui/loader/test__viv_monitor.js
node tests/unit/vault_ui/loader/test__viv_credential_tiers.js
node tests/unit/vault_ui/loader/test__app_permissions_vault_mount.js
node tests/unit/vault_ui/loader/test__sg_app_stub.js
node tests/unit/vault_ui/loader/test__app_frame_bootstrap.js
node tests/unit/vault_ui/loader/test__app_shell_nav_helpers.js
node tests/unit/vault_ui/loader/test__app_shell_bridge_build.js
node tests/unit/vault_ui/loader/test__app_shell_llm_bridge.js
node tests/unit/vault_ui/loader/test__app_hud_config.js
node tests/unit/vault_ui/loader/test__sgit_diff.js
node tests/unit/vault_ui/loader/test__sg_embed_helpers.js
node tests/unit/vault_ui/loader/test__embed_protocol.js
node tests/unit/vault_ui/loader/test__embed_receiver.js
node tests/unit/vault_ui/loader/test__sg_append_client.js
node tests/unit/vault_ui/loader/test__sg_append_checker.js
node tests/unit/vault_ui/loader/test__bundle_freshness.js
echo ""
echo "=== All vault unit tests passed ==="
