#!/usr/bin/env python3
"""
build-kernel-shell-bundle.py — concatenate the kernel shell + dependencies into a
single self-contained HTML string and emit it as a JS module that sets
globalThis.KERNEL_SHELL_HTML.

Why: a `null`-origin (sandboxed srcdoc) iframe cannot load `<script src=...>`
subresources from the same origin (Origin: null CORS wall). So when a parent
kernel spawns a child kernel, it must inject EVERYTHING the child needs as one
self-contained HTML document. This script builds that document.

Run from repo root:
    python3 scripts/build-kernel-shell-bundle.py
Or as part of any build/CI step.

Output: sgraph_ai_app_send__ui__vault/.../js/components/app-shell/kernel-shell-bundle.js
"""
import json
import os
import sys

ROOT = 'sgraph_ai_app_send__ui__vault/v0/v0.2/v0.2.3/_common'

# Dependency order — same order the /app page loads, with kernel-* added.
# kernel-app-handlers.js and kernel-bootstrap.js are bundled at the end so the
# child kernel runs the SAME policy-enforcing code paths that the Node test suite
# exercises (no more divergence between TestKernel and the shipped child).
SCRIPTS = [
    'js/components/app-shell/app-permissions.js',
    'js/components/app-shell/secure-channel-envelope.js',
    'js/components/app-shell/secure-channel.js',
    'js/lib/sg-vault/sg-vault-crypto.js',
    'js/lib/sg-vault/sg-vault-object-store.js',
    'js/lib/sg-vault/sg-vault-ref-manager.js',
    'js/lib/sg-vault/sg-vault-commit.js',
    'js/lib/sg-vault/sg-vault.js',
    'js/lib/sg-vault/sg-vault--file-ops.js',
    'js/lib/sg-vault/sg-vault--folder-ops.js',
    'js/lib/sg-vault/sg-vault--sync.js',
    'js/lib/sg-vault/sg-vault--history.js',
    'js/lib/sg-vault/sg-vault--branches.js',
    'js/lib/sg-send/sg-send-crypto.js',
    'js/lib/sg-send/sg-send.js',
    'js/adapters/vault-data-source.js',
    'js/adapters/composite-data-source.js',
    'js/lib/links/vault-links.js',
    'js/components/app-shell/kernel-mounts.js',
    'js/components/app-shell/kernel-broker.js',
    'js/components/app-shell/kernel-parent.js',
    'js/components/app-shell/kernel-app-handlers.js',
    'js/components/app-shell/kernel-bootstrap.js',
]

# Inline child-side kernel boot listener. The ONE window.message listener — grabs
# the transferred port and hands it to bootKernelOnPort. That function lives in
# kernel-bootstrap.js (and is unit-tested there); the only line that cannot be
# unit-tested is the `window.addEventListener` here, because it touches `window`.
KERNEL_BOOTSTRAP_JS = r"""
(function () {
    'use strict';
    function boot(e) {
        if (!e.data || e.data.type !== 'init') return;
        window.removeEventListener('message', boot);
        var port = e.ports && e.ports[0];
        if (!port) { console.error('[kernel] no port on init'); return; }
        globalThis.bootKernelOnPort(port, { cid: e.data.cid, expectSensitive: true })
            .catch(function (err) { console.error('[kernel] handshake failed', err); });
    }
    window.addEventListener('message', boot);
})();
""".strip()


def read_script(rel_path: str) -> str:
    path = os.path.join(ROOT, rel_path)
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def build_bundle() -> str:
    scripts_html = []
    for rel in SCRIPTS:
        scripts_html.append(f'<script>\n{read_script(rel)}\n</script>')
    scripts_html.append(f'<script>\n{KERNEL_BOOTSTRAP_JS}\n</script>')

    html = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">\n'
        + '\n'.join(scripts_html)
        + '\n</head><body></body></html>'
    )

    bundle = '/* AUTO-GENERATED by scripts/build-kernel-shell-bundle.py — do not edit by hand */\n'
    bundle += '(function () { "use strict"; globalThis.KERNEL_SHELL_HTML = '
    bundle += json.dumps(html)
    bundle += '; })();\n'
    return bundle


def main() -> int:
    to_stdout = ('--stdout' in sys.argv[1:])

    missing = [s for s in SCRIPTS if not os.path.exists(os.path.join(ROOT, s))]
    if missing:
        for m in missing:
            print(f'  MISSING: {m}', file=sys.stderr)
        print('Cannot build kernel-shell bundle.', file=sys.stderr)
        return 1

    bundle = build_bundle()

    if to_stdout:
        # L3 freshness check: tests compare this output against the committed file
        # without mutating it.
        sys.stdout.write(bundle)
        return 0

    out_path = os.path.join(ROOT, 'js/components/app-shell/kernel-shell-bundle.js')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(bundle)

    print(f'  wrote {len(bundle):,} bytes → {out_path}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
