#!/usr/bin/env python3
"""Inject build version info into the User UI as a generated JS file.

Reads the app version from sgraph_ai_app_send/version, reads the UI version
from the manifest.json, and writes a build-info.js file into _common/js/.

This file is a CI-generated artifact — it should NOT be committed to git.
The footer component reads window.SGRAPH_BUILD to display version info.

Usage:
    python scripts/inject_build_version.py
    python scripts/inject_build_version.py --version v0.2.0
    python scripts/inject_build_version.py --dry-run
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT       = Path(__file__).parent.parent
APP_VERSION_FILE = REPO_ROOT / 'sgraph_ai_app_send' / 'version'
UI_BASE          = REPO_ROOT / 'sgraph_ai_app_send__ui__user'

BUILD_INFO_TEMPLATE = """\
/* Generated by CI — do not edit manually.
   Source: scripts/inject_build_version.py
   Build:  {build_time} */
window.SGRAPH_BUILD = {{
    appVersion : '{app_version}',
    uiVersion  : '{ui_version}',
    buildTime  : '{build_time}'
}};
"""


def version_to_ifd_path(version):
    clean = version.lstrip('v')
    parts = clean.split('.')
    if len(parts) == 3:
        major, minor, patch = parts
        return f'v{major}/v{major}.{minor}/v{major}.{minor}.{patch}'
    return version


def main():
    parser = argparse.ArgumentParser(description='Inject build version into UI')
    parser.add_argument('--version', type=str, default='v0.2.0',
                        help='UI version to target (default: v0.2.0)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Print what would be written without writing')
    args = parser.parse_args()

    # Read app version
    if not APP_VERSION_FILE.exists():
        print(f"ERROR: App version file not found: {APP_VERSION_FILE}")
        return 1
    app_version = APP_VERSION_FILE.read_text().strip()

    # Resolve UI version dir
    ifd_path    = version_to_ifd_path(args.version)
    version_dir = UI_BASE / ifd_path

    # Read UI version from manifest
    manifest_path = version_dir / 'manifest.json'
    if manifest_path.exists():
        with open(manifest_path) as f:
            manifest = json.load(f)
        ui_version = f"v{manifest.get('version', args.version.lstrip('v'))}"
    else:
        ui_version = args.version

    # Build timestamp
    build_time = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')

    # Generate content
    content = BUILD_INFO_TEMPLATE.format(
        app_version=app_version,
        ui_version=ui_version,
        build_time=build_time,
    )

    target = version_dir / '_common' / 'js' / 'build-info.js'

    print(f"SGraph Send — Build Version Injection")
    print(f"  App version : {app_version}")
    print(f"  UI version  : {ui_version}")
    print(f"  Build time  : {build_time}")
    print(f"  Target      : {target}")

    if args.dry_run:
        print(f"\n[dry-run] Would write:\n{content}")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding='utf-8')
    print(f"\n  Written: {target}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
