#!/bin/bash
# ---------------------------------------------------------------------------
# Combined local dev server for the v0.4.x send UI (share + open trees).
#
# Boots BOTH trees behind one localhost reverse-proxy origin so that:
#   - the sender (share) wizard at /en-gb/share/ and
#   - the receiver (open) pages at /en-gb/open/{,browse,download,gallery,v,view,s}/
# share a single origin (no CORS issues for round-trip Playwright tests).
#
# Mirrors the production CloudFront routing:
#   /api/*           → Lambda
#   /en-gb/share/*   → S3 (share tree)
#   /en-gb/open/*    → S3 (open tree)
#
# IFD overlay pattern: copy v0.4.0 base first, then overlay v0.4.x+ in
# version order for each tree.
#
# Web Crypto API (AES-256-GCM) requires either https:// or http://localhost
# — using 127.0.0.1 will NOT work. This script binds to localhost.
#
# Plan reference: team/roles/architect/reviews/05/10/v0.27.29__plan__v0.4.0-major-release.md §13 Q6
# ---------------------------------------------------------------------------
PORT=10062
API_ENDPOINT="${SGRAPH_API_ENDPOINT:-https://dev.send.sgraph.ai}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

SHARE_DIR="$REPO_ROOT/sgraph_ai_app_send__ui__share"
OPEN_DIR="$REPO_ROOT/sgraph_ai_app_send__ui__open"
SERVE_DIR="$REPO_ROOT/.local-server-send"

# ─── Discover all v0.4.x versions in each tree (IFD overlay pattern) ────────
SHARE_VERSIONS=$(ls -d "$SHARE_DIR/v0/v0.4"/v0.4.* 2>/dev/null | xargs -n1 basename | sort -t. -k3 -n)
OPEN_VERSIONS=$(ls  -d "$OPEN_DIR/v0/v0.4"/v0.4.* 2>/dev/null | xargs -n1 basename | sort -t. -k3 -n)
SHARE_LATEST=$(echo "$SHARE_VERSIONS" | tail -1)
OPEN_LATEST=$(echo  "$OPEN_VERSIONS"  | tail -1)

if [ -z "$SHARE_LATEST" ] && [ -z "$OPEN_LATEST" ]; then
    echo "WARNING: No v0.4.x versions found in either tree yet."
    echo "  Share tree: $SHARE_DIR/v0/v0.4/"
    echo "  Open  tree: $OPEN_DIR/v0/v0.4/"
    echo "Phase A0 scaffolds the empty trees; files arrive in Phase A-share / A-open."
fi

cleanup() {
    echo ""
    echo "Stopping send local server..."
    rm -rf "$SERVE_DIR"
}
trap cleanup EXIT

# ─── Build the combined serve directory ──────────────────────────────────────
echo "Building combined send local server directory..."
rm -rf "$SERVE_DIR"
mkdir -p "$SERVE_DIR"

# Share tree → en-gb/{share,_common,i18n,test-files}/
# v0.4.0 keeps its shared assets (_common, i18n, test-files) UNDER en-gb/ so they
# isolate to latest/en-gb/_common/ on S3 and never collide with the v0.3.x user
# tree's latest/_common/. Copy the whole en-gb/ subtree to preserve that layout.
if [ -n "$SHARE_VERSIONS" ]; then
    echo "  Share tree versions (overlay order): $SHARE_VERSIONS"
    for VERSION in $SHARE_VERSIONS; do
        UI_DIR="$SHARE_DIR/v0/v0.4/$VERSION"
        if [ ! -d "$UI_DIR" ]; then
            echo "    WARNING: $UI_DIR not found, skipping"
            continue
        fi
        if [ -d "$UI_DIR/en-gb" ]; then
            mkdir -p "$SERVE_DIR/en-gb"
            cp -rL "$UI_DIR/en-gb/"* "$SERVE_DIR/en-gb/" 2>/dev/null || true
        fi
    done
fi

# Open tree → en-gb/{open,_common,i18n}/ (open's _common overlays share's; the
# Phase A0 checksum check ensures the duplicated files are byte-identical, so
# this overlay is safe at runtime).
if [ -n "$OPEN_VERSIONS" ]; then
    echo "  Open  tree versions (overlay order): $OPEN_VERSIONS"
    for VERSION in $OPEN_VERSIONS; do
        UI_DIR="$OPEN_DIR/v0/v0.4/$VERSION"
        if [ ! -d "$UI_DIR" ]; then
            echo "    WARNING: $UI_DIR not found, skipping"
            continue
        fi
        if [ -d "$UI_DIR/en-gb" ]; then
            mkdir -p "$SERVE_DIR/en-gb"
            cp -rL "$UI_DIR/en-gb/"* "$SERVE_DIR/en-gb/" 2>/dev/null || true
        fi
    done
fi

# ─── Inject build-info.js ────────────────────────────────────────────────────
mkdir -p "$SERVE_DIR/en-gb/_common/js"
UI_VERSION_LABEL="${SHARE_LATEST:-${OPEN_LATEST:-none}}"
cat > "$SERVE_DIR/en-gb/_common/js/build-info.js" <<JSEOF
/* Generated by send__run-locally.sh — local development only */
window.SGRAPH_BUILD = {
    appVersion  : 'local-dev',
    uiVersion   : '$UI_VERSION_LABEL',
    shareVersion: '${SHARE_LATEST:-none}',
    openVersion : '${OPEN_LATEST:-none}',
    buildTime   : '$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    apiEndpoint : '$API_ENDPOINT'
};
JSEOF

# ─── Root redirect ───────────────────────────────────────────────────────────
cat > "$SERVE_DIR/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html>
<head><meta http-equiv="refresh" content="0;url=/en-gb/share/"></head>
<body><a href="/en-gb/share/">Redirecting to /en-gb/share/ ...</a></body>
</html>
HTMLEOF

# ─── Start server ────────────────────────────────────────────────────────────
echo ""
echo "Starting send.sgraph.ai combined local server..."
echo "  Root:           $SERVE_DIR"
echo "  Share latest:   ${SHARE_LATEST:-none}"
echo "  Open  latest:   ${OPEN_LATEST:-none}"
echo ""
echo "  URLs:"
echo "    Home (share):   http://localhost:$PORT/"
echo "    Sender wizard:  http://localhost:$PORT/en-gb/share/"
echo "    Receiver land:  http://localhost:$PORT/en-gb/open/"
echo "    Browse:         http://localhost:$PORT/en-gb/open/browse/"
echo "    Download:       http://localhost:$PORT/en-gb/open/download/"
echo "    Gallery:        http://localhost:$PORT/en-gb/open/gallery/"
echo "    Secret view:    http://localhost:$PORT/en-gb/open/s/"
echo ""
echo "  Backend API:    $API_ENDPOINT"
echo "    Override:     SGRAPH_API_ENDPOINT=https://send.sgraph.ai ./scripts/send__run-locally.sh"
echo ""
echo "  IMPORTANT: Use 'localhost' not '127.0.0.1' (Web Crypto requires secure context)"
echo ""
python3 -m http.server $PORT --directory "$SERVE_DIR" --bind localhost
