#!/bin/bash
# ---------------------------------------------------------------------------
# Local dev server for the send UI (dev.send.sgraph.ai)
#
# Serves the user UI as a pure static file server, pointing API calls
# at a remote backend (default: https://dev.send.sgraph.ai).
#
# This mirrors production where CloudFront routes:
#   /* → S3 static files
#   /api/* → Lambda
#
# The send UI uses Web Crypto API (AES-256-GCM) which requires either:
#   - https:// (production)
#   - http://localhost (local dev — this script)
# Using 127.0.0.1 will NOT work for Web Crypto.
# ---------------------------------------------------------------------------
PORT=10062
API_ENDPOINT="${SGRAPH_API_ENDPOINT:-https://dev.send.sgraph.ai}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
STATIC_DIR="$REPO_ROOT/sgraph_ai_app_send__ui__user"
UI_VERSION="v0.3.0"
SERVE_DIR="$REPO_ROOT/.local-server-user"

UI_DIR="$STATIC_DIR/v0/v0.3/$UI_VERSION"

# Clean up on exit
cleanup() {
    echo ""
    echo "Stopping server..."
    rm -rf "$SERVE_DIR"
}
trap cleanup EXIT

if [ ! -d "$UI_DIR" ]; then
    echo "ERROR: UI not found: $UI_DIR"
    exit 1
fi

# ─── Build the local serve directory ──────────────────────────────────────────
# v0.3.0 is self-contained — all components (upload + download) live in
# its own _common directory. No v0.2.x overlay merging needed.

echo "Building local server directory (mirroring production URL structure)..."
rm -rf "$SERVE_DIR"
mkdir -p "$SERVE_DIR"

# Copy v0.3.0's _common (resolving symlinks)
cp -rL "$UI_DIR/_common" "$SERVE_DIR/_common"

# ─── Locale pages ────────────────────────────────────────────────────────────
# en-gb/index.html           → upload page
# en-gb/download/index.html  → download page
# en-gb/browse|gallery|v|view/ → viewer routes

mkdir -p "$SERVE_DIR/en-gb"

# Upload page
cp "$UI_DIR/en-gb/index.html" "$SERVE_DIR/en-gb/index.html"

# Download + viewer route pages (each has its own index.html)
for route in download browse gallery v view; do
    if [ -d "$UI_DIR/en-gb/$route" ]; then
        mkdir -p "$SERVE_DIR/en-gb/$route"
        cp "$UI_DIR/en-gb/$route/index.html" "$SERVE_DIR/en-gb/$route/index.html"
    fi
done

# Welcome page
if [ -d "$UI_DIR/en-gb/welcome" ]; then
    cp -r "$UI_DIR/en-gb/welcome" "$SERVE_DIR/en-gb/welcome"
fi

# ─── Inject build-info.js ────────────────────────────────────────────────────
mkdir -p "$SERVE_DIR/_common/js"
cat > "$SERVE_DIR/_common/js/build-info.js" <<JSEOF
/* Generated by user__run-locally.sh — local development only */
window.SGRAPH_BUILD = {
    appVersion  : 'local-dev',
    uiVersion   : '$UI_VERSION',
    buildTime   : '$(date -u +%Y-%m-%dT%H:%M:%SZ)',
    apiEndpoint : '$API_ENDPOINT'
};
JSEOF

# ─── Test files ──────────────────────────────────────────────────────────────
# The send-test-files component resolves ../test-files from en-gb/ → /test-files/
if [ -d "$UI_DIR/test-files" ]; then
    ln -sf "$UI_DIR/test-files" "$SERVE_DIR/test-files"
fi

# ─── Root redirect ───────────────────────────────────────────────────────────
cat > "$SERVE_DIR/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html>
<head><meta http-equiv="refresh" content="0;url=/en-gb/"></head>
<body><a href="/en-gb/">Redirecting to /en-gb/...</a></body>
</html>
HTMLEOF

# ─── Start server ────────────────────────────────────────────────────────────
echo ""
echo "Starting send.sgraph.ai local server (v0.3.0 — unified upload + download)..."
echo "  Root:     $SERVE_DIR"
echo "  UI:       $UI_DIR"
echo ""
echo "  URLs:"
echo "    Home:           http://localhost:$PORT/"
echo "    Upload:         http://localhost:$PORT/en-gb/"
echo "    Download:       http://localhost:$PORT/en-gb/download/"
echo "    Browse:         http://localhost:$PORT/en-gb/browse/"
echo "    Gallery:        http://localhost:$PORT/en-gb/gallery/"
echo ""
echo "  Backend API:    $API_ENDPOINT"
echo "    Override:     SGRAPH_API_ENDPOINT=https://send.sgraph.ai ./scripts/user__run-locally.sh"
echo ""
echo "  IMPORTANT: Use 'localhost' not '127.0.0.1' (Web Crypto requires secure context)"
echo ""
python3 -m http.server $PORT --directory "$SERVE_DIR" --bind localhost
