#!/bin/bash
# ---------------------------------------------------------------------------
# Local dev server for the vault UI (dev.vault.sgraph.ai)
#
# In production, the CI deploy script flattens the versioned IFD structure:
#   vault/v0/v0.1/v0.1.2/en-gb/   →  latest/en-gb/
#   vault/v0/v0.1/v0.1.2/_common/  →  latest/_common/
#   vault/v0/v0.1/v0.1.2/i18n/     →  latest/i18n/
#
# This script replicates that locally by creating symlinks in a temporary
# directory that mirrors the production URL structure.
#
# The vault UI uses Web Crypto API (AES-256-GCM) which requires either:
#   - https:// (production)
#   - http://localhost (local dev — this script)
# Using 127.0.0.1 will NOT work for Web Crypto.
# ---------------------------------------------------------------------------
PORT=10063
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
STATIC_DIR="$REPO_ROOT/sgraph_ai_app_send__ui__vault"
UI_VERSION="v0.1.3"
IFD_PATH="v0/v0.1/$UI_VERSION"
SERVE_DIR="$REPO_ROOT/.local-server-vault"

# Clean up on exit
cleanup() {
    echo ""
    echo "Stopping server..."
    rm -rf "$SERVE_DIR"
}
trap cleanup EXIT

# Build the local serve directory with symlinks
echo "Building local server directory (mirroring production URL structure)..."
rm -rf "$SERVE_DIR"
mkdir -p "$SERVE_DIR"

# Versioned content → root (en-gb/, _common/, i18n/, etc.)
CONTENT_DIR="$STATIC_DIR/$IFD_PATH"
if [ ! -d "$CONTENT_DIR" ]; then
    echo "ERROR: Content directory not found: $CONTENT_DIR"
    exit 1
fi

# Symlink locale folders (en-gb/, etc.)
for locale_dir in "$CONTENT_DIR"/*/; do
    dirname=$(basename "$locale_dir")
    if [ "$dirname" != "_common" ] && [ "$dirname" != "i18n" ] && [ -d "$locale_dir" ]; then
        ln -sf "$locale_dir" "$SERVE_DIR/$dirname"
    fi
done

# Copy _common (not symlink) so we can inject build-info.js
cp -r "$CONTENT_DIR/_common" "$SERVE_DIR/_common"

# Symlink i18n/
[ -d "$CONTENT_DIR/i18n" ] && ln -sf "$CONTENT_DIR/i18n" "$SERVE_DIR/i18n"

# Copy root files (index.html, etc.)
for f in "$CONTENT_DIR"/*.html "$CONTENT_DIR"/*.json; do
    [ -f "$f" ] && [ "$(basename "$f")" != "index.html" ] && cp "$f" "$SERVE_DIR/$(basename "$f")"
done

# Inject build-info.js for local dev (CI generates this in production)
mkdir -p "$SERVE_DIR/_common/js"
cat > "$SERVE_DIR/_common/js/build-info.js" <<JSEOF
/* Generated by vault__run-locally.sh — local development only */
window.SGRAPH_BUILD = {
    appVersion : 'local-dev',
    uiVersion  : '$UI_VERSION',
    buildTime  : '$(date -u +%Y-%m-%dT%H:%M:%SZ)'
};
JSEOF

# Create a root index.html that redirects to /en-gb/
cat > "$SERVE_DIR/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html>
<head><meta http-equiv="refresh" content="0;url=/en-gb/"></head>
<body><a href="/en-gb/">Redirecting to /en-gb/...</a></body>
</html>
HTMLEOF

echo ""
echo "Starting vault.sgraph.ai local server..."
echo "  Root:       $SERVE_DIR"
echo "  Content:    $CONTENT_DIR"
echo ""
echo "  URLs:"
echo "    Home:           http://localhost:$PORT/"
echo "    Vault:          http://localhost:$PORT/en-gb/"
echo ""
echo "  IMPORTANT: Use 'localhost' not '127.0.0.1' (Web Crypto requires secure context)"
echo ""
echo "  Backend:"
echo "    Default:        https://send.sgraph.ai (production)"
echo "    Local backend:  Run ./scripts/user__run-locally.sh in another terminal (port 10062)"
echo "                    Then set data-endpoint=\"http://localhost:10062\" on <vault-entry>"
echo ""
python3 -m http.server $PORT --directory "$SERVE_DIR" --bind localhost
