name: CI Pipeline - RELEASE
on:
  workflow_dispatch:

jobs:
  deploy-qa:
    uses: ./.github/workflows/ci-pipeline.yml
    with:
      git_branch          : 'main'
      should_increment_tag: false
      should_publish_pypi : false
      target_deploy       : ''
    secrets: inherit